/* @generated by Namix — DO NOT EDIT */
/* Rust: route::main::home  →  TS: route.home()（与 .name("home") 对齐） */
/* 带参: route.profile({ id: 1 }) */

export const routes = {
  "__namix.api.a": { uri: "/api/a", methods: ["POST"] as const },
  "__namix.build": { uri: "/build/*path", methods: ["GET"] as const },
  "__namix.health": { uri: "/__namix/health", methods: ["GET"] as const },
  "__namix.props": { uri: "/__namix/props/:key", methods: ["GET"] as const },
  "__namix.routes": { uri: "/__namix/routes", methods: ["GET"] as const },
  "chat": { uri: "/chat", methods: ["GET"] as const },
  "demo": { uri: "/demo", methods: ["GET"] as const },
  "home": { uri: "/", methods: ["GET"] as const },
  "island": { uri: "/island", methods: ["GET"] as const },
  "login": { uri: "/login", methods: ["GET"] as const },
  "logout": { uri: "/logout", methods: ["GET"] as const },
  "mailbox": { uri: "/mailbox", methods: ["GET"] as const },
  "me": { uri: "/me", methods: ["GET"] as const },
  "me.submit": { uri: "/me", methods: ["POST"] as const },
  "posts": { uri: "/posts", methods: ["GET"] as const },
  "posts.submit": { uri: "/posts", methods: ["POST"] as const },
  "profile": { uri: "/profile/:id", methods: ["GET"] as const },
  "register": { uri: "/register", methods: ["GET"] as const },
  "sse.ticks": { uri: "/sse/ticks", methods: ["GET"] as const },
  "vip": { uri: "/vip", methods: ["GET"] as const },
  "webhooks.mail.inbound": { uri: "/webhooks/mail/inbound", methods: ["POST"] as const },
  "ws.chat": { uri: "/ws/chat", methods: ["WS"] as const },
  "ws.echo": { uri: "/ws/echo", methods: ["WS"] as const },
} as const;

export type RouteName = keyof typeof routes;

function fill(uri: string, params?: Record<string, string | number>): string {
let out = uri;
if (params) {
for (const [k, v] of Object.entries(params)) {
out = out.replace(`:${k}`, String(v));
}
}
if (out.split('/').some((s) => s.startsWith(':'))) {
throw new Error(`missing route params: ${out}`);
}
return out;
}

/** 字符串名解析（兼容旧写法） */
export function resolveRoute(
name: RouteName,
params?: Record<string, string | number>
): string {
return fill(routes[name].uri, params);
}

/** 与命名路由短名同构：route.login() ≡ .name("login") */
export const route = {
  chat: Object.assign(() => fill(routes["chat"].uri), {
    routeName: "chat" as const,
    uri: "/chat" as const,
  }),
  demo: Object.assign(() => fill(routes["demo"].uri), {
    routeName: "demo" as const,
    uri: "/demo" as const,
  }),
  home: Object.assign(() => fill(routes["home"].uri), {
    routeName: "home" as const,
    uri: "/" as const,
  }),
  island: Object.assign(() => fill(routes["island"].uri), {
    routeName: "island" as const,
    uri: "/island" as const,
  }),
  login: Object.assign(() => fill(routes["login"].uri), {
    routeName: "login" as const,
    uri: "/login" as const,
  }),
  logout: Object.assign(() => fill(routes["logout"].uri), {
    routeName: "logout" as const,
    uri: "/logout" as const,
  }),
  mailbox: Object.assign(() => fill(routes["mailbox"].uri), {
    routeName: "mailbox" as const,
    uri: "/mailbox" as const,
  }),
  me: Object.assign(() => fill(routes["me"].uri), {
    routeName: "me" as const,
    uri: "/me" as const,
    submit: Object.assign(() => fill(routes["me.submit"].uri), {
      routeName: "me.submit" as const,
      uri: "/me" as const,
    }),
  }),
  posts: Object.assign(() => fill(routes["posts"].uri), {
    routeName: "posts" as const,
    uri: "/posts" as const,
    submit: Object.assign(() => fill(routes["posts.submit"].uri), {
      routeName: "posts.submit" as const,
      uri: "/posts" as const,
    }),
  }),
  profile: Object.assign(
    (params: { id: string | number }) => fill(routes["profile"].uri, params),
    {
      routeName: "profile" as const,
      uri: "/profile/:id" as const,
    }
  ),
  register: Object.assign(() => fill(routes["register"].uri), {
    routeName: "register" as const,
    uri: "/register" as const,
  }),
  sse: {
    ticks: Object.assign(() => fill(routes["sse.ticks"].uri), {
      routeName: "sse.ticks" as const,
      uri: "/sse/ticks" as const,
    }),
  },
  vip: Object.assign(() => fill(routes["vip"].uri), {
    routeName: "vip" as const,
    uri: "/vip" as const,
  }),
  webhooks: {
    mail: {
      inbound: Object.assign(() => fill(routes["webhooks.mail.inbound"].uri), {
        routeName: "webhooks.mail.inbound" as const,
        uri: "/webhooks/mail/inbound" as const,
      }),
    },
  },
  ws: {
    chat: Object.assign(() => fill(routes["ws.chat"].uri), {
      routeName: "ws.chat" as const,
      uri: "/ws/chat" as const,
    }),
    echo: Object.assign(() => fill(routes["ws.echo"].uri), {
      routeName: "ws.echo" as const,
      uri: "/ws/echo" as const,
    }),
  },
} as const;

type RouteFn = {
(name: RouteName, params?: Record<string, string | number>): string;
} & typeof route;

const routeCallable = Object.assign(
((name: RouteName, params?: Record<string, string | number>) =>
resolveRoute(name, params)) as RouteFn,
route
);

export default routeCallable;
