//! 供业务包 `build.rs` 调用。
//!
//! 单应用默认核心只有 `controllers` / `routes` / `middleware`；
//! `models` / `services` / `validators` / `pages`（views）等由 `namix.toml [features]` 开关。

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

/// 业务应用名（可按项目扩展）。
pub const APPS: &[&str] = &["www", "user", "admin"];

const APP_CORE_DIRS: &[&str] = &["controllers", "middleware", "routes"];
/// 多应用 common：仅 middleware 始终存在；其余走 [features]。
const COMMON_CORE_DIRS: &[&str] = &["middleware"];
/// `(namix.toml [features] 键, 目录名)` — 关闭时只从生成的模块树排除，绝不删除源码。
const FEATURE_DIRS: &[(&str, &str)] = &[
    ("models", "models"),
    ("services", "services"),
    ("validators", "validators"),
    ("requests", "requests"),
    ("events", "events"),
    ("listeners", "listeners"),
    ("seeders", "seeders"),
];
/// `nx make` 生成后只要目录存在就参与编译；这些是框架能力，不需要额外 feature。
const OPTIONAL_CODE_DIRS: &[&str] = &["policies", "jobs", "mails", "notifications"];
const FEATURE_MARKER: &str = ".namix-feature";

/// 单应用同步：扁平 `src/{controllers,routes,middleware}` + `[features]` 目录。
pub fn sync_single() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let src_dir = manifest_dir.join("src");
    let config_path = manifest_dir.join("namix.toml");

    println!("cargo:rerun-if-changed={}", config_path.display());
    println!("cargo:rerun-if-changed={}", src_dir.display());
    let features = read_features(&config_path);

    const CORE: &[&str] = &["controllers", "middleware", "routes"];

    for &dir_name in CORE {
        let dir = src_dir.join(dir_name);
        ensure_dir(&dir);
        watch_dir(&dir);
        generate_mod_rs(&dir);
    }

    let mut active: Vec<&str> = CORE.to_vec();
    for &(feature, dir_name) in FEATURE_DIRS {
        let dir = src_dir.join(dir_name);
        if features.get(feature).copied().unwrap_or(false) {
            ensure_feature_dir(&dir, feature);
            active.push(dir_name);
        }
        watch_dir(&dir);
        if dir.is_dir() {
            generate_mod_rs(&dir);
        }
    }
    for &dir_name in OPTIONAL_CODE_DIRS {
        let dir = src_dir.join(dir_name);
        if dir.is_dir() {
            watch_dir(&dir);
            generate_mod_rs(&dir);
            active.push(dir_name);
        }
    }

    let views = src_dir.join("views");
    let pages = src_dir.join("pages");
    let legacy_props = src_dir.join("props");
    if features.get("pages").copied().unwrap_or(false) {
        ensure_feature_dir(&views, "pages");
        watch_dir(&views);
        if legacy_props.is_dir() && !pages.is_dir() {
            let _ = fs::rename(&legacy_props, &pages);
        }
        if pages.is_dir() {
            watch_dir(&pages);
            generate_pages_mod_rs(&pages);
            if !active.contains(&"pages") {
                active.push("pages");
            }
        }
        generate_frontend_fields(&src_dir);
        generate_view_registry(&src_dir);
    } else {
        // Feature toggles control compilation, not ownership of user source.
        // Keeping these directories makes malformed/temporary configuration
        // changes non-destructive and lets the feature be re-enabled safely.
        watch_dir(&views);
        watch_dir(&pages);
        watch_dir(&legacy_props);
        write_view_rs(&src_dir, &BTreeMap::new());
    }

    let mut body = String::from("// @generated by namix-build — DO NOT EDIT\n\n");
    for name in &active {
        body.push_str("pub mod ");
        body.push_str(name);
        body.push_str(";\n");
    }
    write_if_changed(&src_dir.join("namix_modules.rs"), &body);
    generate_route_names(&src_dir);
}

/// 多应用同步：一份代码，common 复用，各端只写自己的控制器/路由。
pub fn sync() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let src_dir = manifest_dir.join("src");
    let config_path = manifest_dir.join("namix.toml");

    println!("cargo:rerun-if-changed={}", config_path.display());
    println!("cargo:rerun-if-changed={}", src_dir.display());
    let features = read_features(&config_path);

    let common = src_dir.join("common");
    ensure_dir(&common);
    for &dir_name in COMMON_CORE_DIRS {
        let dir = common.join(dir_name);
        ensure_dir(&dir);
        watch_dir(&dir);
        generate_mod_rs(&dir);
    }
    for &(feature, dir_name) in FEATURE_DIRS {
        let dir = common.join(dir_name);
        if features.get(feature).copied().unwrap_or(false) {
            ensure_feature_dir(&dir, feature);
        }
        watch_dir(&dir);
        if dir.is_dir() {
            generate_mod_rs(&dir);
        }
    }
    let mut common_mods: Vec<&str> = COMMON_CORE_DIRS.to_vec();
    for &(feature, dir_name) in FEATURE_DIRS {
        if features.get(feature).copied().unwrap_or(false) {
            common_mods.push(dir_name);
        }
    }
    for &dir_name in OPTIONAL_CODE_DIRS {
        let dir = common.join(dir_name);
        if dir.is_dir() {
            watch_dir(&dir);
            generate_mod_rs(&dir);
            common_mods.push(dir_name);
        }
    }
    generate_package_mod(&common, &common_mods);
    watch_dir(&common);

    let views = src_dir.join("views");
    if features.get("pages").copied().unwrap_or(false) {
        ensure_feature_dir(&views, "pages");
        watch_dir(&views);
        generate_frontend_fields(&src_dir);
        generate_view_registry(&src_dir);
    } else {
        watch_dir(&views);
        watch_dir(&common.join("pages"));
        write_view_rs(&src_dir, &BTreeMap::new());
    }

    for &app in APPS {
        let app_dir = src_dir.join(app);
        ensure_dir(&app_dir);
        let mut children: Vec<&str> = APP_CORE_DIRS.to_vec();
        for &dir_name in APP_CORE_DIRS {
            let dir = app_dir.join(dir_name);
            ensure_dir(&dir);
            watch_dir(&dir);
            generate_mod_rs(&dir);
        }
        let app_validators = app_dir.join("validators");
        if app_validators.is_dir() {
            watch_dir(&app_validators);
            generate_mod_rs(&app_validators);
            children.push("validators");
        }
        generate_package_mod(&app_dir, &children);
        watch_dir(&app_dir);
    }

    generate_route_names(&src_dir);
}

fn read_features(path: &Path) -> BTreeMap<String, bool> {
    let raw = fs::read_to_string(path)
        .unwrap_or_else(|error| panic!("读取 Namix 配置失败 {}: {error}", path.display()));
    let value = toml::from_str::<toml::Value>(&raw)
        .unwrap_or_else(|error| panic!("解析 Namix 配置失败 {}: {error}", path.display()));
    let mut map = BTreeMap::new();
    if let Some(features) = value.get("features") {
        let table = features.as_table().unwrap_or_else(|| {
            panic!(
                "Namix 配置 {} 中 [features] 必须是 TOML table",
                path.display()
            )
        });
        for (k, v) in table {
            let enabled = v.as_bool().unwrap_or_else(|| {
                panic!(
                    "Namix 配置 {} 中 features.{k} 必须是 true/false",
                    path.display()
                )
            });
            map.insert(k.clone(), enabled);
        }
    }
    map
}

fn ensure_dir(dir: &Path) {
    if !dir.exists() {
        fs::create_dir_all(dir).expect("创建目录失败");
    }
}

fn ensure_feature_dir(dir: &Path, feature: &str) {
    ensure_dir(dir);
    let marker = dir.join(FEATURE_MARKER);
    if !marker.exists() {
        fs::write(
            &marker,
            format!("feature = \"{feature}\"\n# managed by namix-build — do not remove\n"),
        )
        .expect("写入 feature 标记失败");
    }
}

fn watch_dir(dir: &Path) {
    if dir.is_dir() {
        println!("cargo:rerun-if-changed={}", dir.display());
    }
}

fn generate_mod_rs(dir: &Path) {
    if !dir.is_dir() {
        return;
    }
    let modules = list_rs_modules(dir);
    let mut body = String::from(
        "// @generated by namix-build — DO NOT EDIT\n\
         // 新增 .rs 后 cargo check 自动注册。\n\n",
    );
    for name in &modules {
        body.push_str("pub mod ");
        body.push_str(name);
        body.push_str(";\n");
    }
    write_if_changed(&dir.join("mod.rs"), &body);
}

/// `pages/`：页面契约（数据形状 + 渲染模式）。`Demo::new(..).render(&req)`。
fn generate_pages_mod_rs(dir: &Path) {
    if !dir.is_dir() {
        return;
    }
    let modules = list_rs_modules(dir);
    let mut body = String::from(
        "// @generated by namix-build — DO NOT EDIT\n\
         // 新增 .rs 后 cargo check 自动注册；扁平导出页面类型。\n\n",
    );
    for name in &modules {
        body.push_str("pub mod ");
        body.push_str(name);
        body.push_str(";\n");
    }
    if !modules.is_empty() {
        body.push('\n');
        for name in &modules {
            let ty = to_pascal_ident(name);
            body.push_str(&format!("pub use {name}::{ty};\n"));
        }
    }
    write_if_changed(&dir.join("mod.rs"), &body);
}

fn list_rs_modules(dir: &Path) -> Vec<String> {
    let mut modules = Vec::new();
    for entry in fs::read_dir(dir).expect("读取目录失败").flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("rs") {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        if stem == "mod" {
            continue;
        }
        modules.push(stem.to_string());
    }
    modules.sort();
    modules
}

fn generate_package_mod(dir: &Path, children: &[&str]) {
    let mut body = String::from("// @generated by namix-build — DO NOT EDIT\n\n");
    for name in children {
        body.push_str("pub mod ");
        body.push_str(name);
        body.push_str(";\n");
    }
    write_if_changed(&dir.join("mod.rs"), &body);
}

fn write_if_changed(path: &Path, content: &str) {
    if fs::read_to_string(path).ok().as_deref() == Some(content) {
        return;
    }
    fs::write(path, content).unwrap_or_else(|e| panic!("写入 {} 失败: {e}", path.display()));
}

/// 从各应用 `routes/**/*.rs` 扫描命名路由，生成类型化 `route::user::login`。
///
/// 从 `routes/**/*.rs` 收集命名路由 → `OUT_DIR/namix_route_names.rs`。
///
/// 注册处写短字符串 `.name("login")`；使用处 `AppRoute::Login` 或 `route::main::login`。
fn generate_route_names(src_dir: &Path) {
    // app → (leaf_ident → (route_name, uri?))
    let mut apps: BTreeMap<String, BTreeMap<String, CollectedRoute>> = BTreeMap::new();
    let mut uris: BTreeMap<String, String> = BTreeMap::new();

    for &app in APPS {
        let routes_dir = src_dir.join(app).join("routes");
        if routes_dir.is_dir() {
            println!("cargo:rerun-if-changed={}", routes_dir.display());
            visit_rs_files(&routes_dir, &mut |_path, src| {
                let src = strip_rs_comments(src);
                collect_route_path_names(&src, &mut apps);
                collect_string_route_names(&src, &mut apps);
                collect_dsl_route_uris(&src, &mut uris);
            });
        }
    }
    let single_routes = src_dir.join("routes");
    if single_routes.is_dir() {
        println!("cargo:rerun-if-changed={}", single_routes.display());
        visit_rs_files(&single_routes, &mut |_path, src| {
            let src = strip_rs_comments(src);
            collect_route_path_names(&src, &mut apps);
            collect_string_route_names(&src, &mut apps);
            collect_dsl_route_uris(&src, &mut uris);
        });
    }

    for leaves in apps.values_mut() {
        for route in leaves.values_mut() {
            if route.uri.is_none() {
                route.uri = uris.get(&route.name).cloned();
            }
        }
    }

    let mut body = String::from(
        "// @generated by namix-build — DO NOT EDIT\n\
         // 来源：routes 里 name: \"login\" / .name(\"login.submit\")\n\
         // 使用：AppRoute::Login 或 route::main::login（leaf 的 _ → 默认名里的 .）\n\n",
    );

    if apps.is_empty() {
        // 空枚举也要生成，业务 `use crate::prelude::*` 才能找到 `AppRoute`。
        body.push_str("namix::route_names! {\n    main {}\n}\n");
    } else {
        body.push_str("namix::route_names! {\n");
        for (app, leaves) in &apps {
            body.push_str("    ");
            body.push_str(app);
            body.push_str(" {\n");
            for (leaf, route) in leaves {
                let default = format!("{app}.{}", leaf.replace('_', "."));
                body.push_str("        ");
                body.push_str(leaf);
                if route.name != default {
                    body.push_str(" = ");
                    body.push_str(&rust_string_literal(&route.name));
                }
                if let Some(uri) = &route.uri {
                    body.push_str(" => ");
                    body.push_str(&rust_string_literal(uri));
                }
                body.push_str(",\n");
            }
            body.push_str("    }\n");
        }
        body.push_str("}\n");
    }

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    write_if_changed(&out_dir.join("namix_route_names.rs"), &body);
}

#[derive(Clone, Debug)]
struct CollectedRoute {
    name: String,
    uri: Option<String>,
}

fn insert_collected_route(
    apps: &mut BTreeMap<String, BTreeMap<String, CollectedRoute>>,
    app: String,
    leaf: String,
    name: String,
) {
    apps.entry(app)
        .or_default()
        .entry(leaf)
        .or_insert(CollectedRoute { name, uri: None });
}

fn rust_string_literal(value: &str) -> String {
    let mut out = String::from("\"");
    for ch in value.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// 去掉 `//` / `///` / `/* */`，避免注释里的示例污染路由表。
fn strip_rs_comments(src: &str) -> String {
    let mut out = String::with_capacity(src.len());
    let mut chars = src.chars().peekable();
    let mut in_block = false;
    let mut in_string = false;
    while let Some(c) = chars.next() {
        if in_block {
            if c == '*' && chars.peek() == Some(&'/') {
                chars.next();
                in_block = false;
            }
            continue;
        }
        if in_string {
            out.push(c);
            if c == '\\' {
                if let Some(n) = chars.next() {
                    out.push(n);
                }
            } else if c == '"' {
                in_string = false;
            }
            continue;
        }
        match c {
            '"' => {
                in_string = true;
                out.push(c);
            }
            '/' if chars.peek() == Some(&'/') => {
                chars.next();
                for n in chars.by_ref() {
                    if n == '\n' {
                        out.push('\n');
                        break;
                    }
                }
            }
            '/' if chars.peek() == Some(&'*') => {
                chars.next();
                in_block = true;
            }
            _ => out.push(c),
        }
    }
    out
}

fn visit_rs_files(dir: &Path, f: &mut dyn FnMut(&Path, &str)) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            visit_rs_files(&path, f);
        } else if path.extension().and_then(|e| e.to_str()) == Some("rs")
            && let Ok(src) = fs::read_to_string(&path)
        {
            f(&path, &src);
        }
    }
}

fn collect_route_path_names(
    src: &str,
    apps: &mut BTreeMap<String, BTreeMap<String, CollectedRoute>>,
) {
    let mut rest = src;
    while let Some(idx) = rest.find("route::") {
        let before = &rest[..idx];
        let prev = before.chars().last();
        if prev.is_some_and(|c| c.is_ascii_alphanumeric() || c == '_') {
            rest = &rest[idx + 7..];
            continue;
        }
        rest = &rest[idx + 7..];
        if let Some((app, leaf)) = parse_route_path_tail(rest)
            && is_ident(&app)
            && is_ident(&leaf)
        {
            let default = format!("{app}.{}", leaf.replace('_', "."));
            insert_collected_route(apps, app, leaf, default);
        }
    }
}

/// `user::login` / `user::register_submit`（恰好两段）
fn parse_route_path_tail(s: &str) -> Option<(String, String)> {
    let (app, after_app) = split_ident(s)?;
    if !after_app.starts_with("::") {
        return None;
    }
    let (leaf, _) = split_ident(&after_app[2..])?;
    Some((app.to_string(), leaf.to_string()))
}

fn split_ident(s: &str) -> Option<(&str, &str)> {
    let mut end = 0;
    for (i, c) in s.char_indices() {
        if i == 0 {
            if !(c.is_ascii_alphabetic() || c == '_') {
                return None;
            }
        } else if !(c.is_ascii_alphanumeric() || c == '_') {
            end = i;
            break;
        }
        end = i + c.len_utf8();
    }
    if end == 0 {
        return None;
    }
    Some((&s[..end], &s[end..]))
}

fn is_ident(s: &str) -> bool {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' => {}
        _ => return false,
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn collect_string_route_names(
    src: &str,
    apps: &mut BTreeMap<String, BTreeMap<String, CollectedRoute>>,
) {
    for marker in [".name(\"", "name: \"", "name = \""] {
        let mut rest = src;
        while let Some(idx) = rest.find(marker) {
            rest = &rest[idx + marker.len()..];
            let Some(end) = rest.find('"') else {
                break;
            };
            let name = &rest[..end];
            rest = &rest[end + 1..];
            insert_dotted_route_name(name, apps);
        }
    }
}

/// `.name("login")` / `.name("login.submit")` → `main::{login|login_submit}`，路由名保持原串。
fn insert_dotted_route_name(
    name: &str,
    apps: &mut BTreeMap<String, BTreeMap<String, CollectedRoute>>,
) {
    if name.starts_with("__") {
        return;
    }
    let parts: Vec<&str> = name.split('.').filter(|p| !p.is_empty()).collect();
    if parts.is_empty() || !parts.iter().all(|p| is_ident(p)) {
        return;
    }
    let leaf = parts.join("_");
    insert_collected_route(apps, "main".into(), leaf, name.to_string());
}

/// `GET "/profile/:id" => …, name: "profile"` → 名字对应的路径模板。
fn collect_dsl_route_uris(src: &str, uris: &mut BTreeMap<String, String>) {
    const METHODS: [&str; 6] = ["GET ", "POST ", "PUT ", "PATCH ", "DELETE ", "WS "];
    let mut rest = src;
    loop {
        let next = METHODS
            .iter()
            .filter_map(|method| rest.find(method).map(|idx| (idx, *method)))
            .min_by_key(|(idx, _)| *idx);
        let Some((idx, method)) = next else {
            break;
        };
        rest = rest[idx + method.len()..].trim_start();
        if !rest.starts_with('"') {
            continue;
        }
        rest = &rest[1..];
        let Some(end) = rest.find('"') else {
            break;
        };
        let path = rest[..end].to_string();
        rest = &rest[end + 1..];
        let window_len = rest.len().min(400);
        if let Some(name) = first_route_name_in(&rest[..window_len]) {
            uris.entry(name).or_insert(path);
        }
    }
}

fn first_route_name_in(window: &str) -> Option<String> {
    let mut best: Option<(usize, String)> = None;
    for marker in ["name: \"", "name = \"", ".name(\""] {
        let Some(idx) = window.find(marker) else {
            continue;
        };
        let rest = &window[idx + marker.len()..];
        let Some(end) = rest.find('"') else {
            continue;
        };
        let name = rest[..end].to_string();
        if name.starts_with("__") || name.is_empty() {
            continue;
        }
        if best.as_ref().is_none_or(|(best_idx, _)| idx < *best_idx) {
            best = Some((idx, name));
        }
    }
    best.map(|(_, name)| name)
}
/// 扫描 `validators/**/*.rs` 的 FormField enum → `views/generated/fields.ts`
fn generate_frontend_fields(src_dir: &Path) {
    let mut forms: BTreeMap<String, Vec<(String, String)>> = BTreeMap::new();
    for dir_name in ["validators", "common/validators"] {
        let dir = src_dir.join(dir_name);
        if !dir.is_dir() {
            continue;
        }
        println!("cargo:rerun-if-changed={}", dir.display());
        visit_rs_files(&dir, &mut |_path, src| {
            let src = strip_rs_comments(src);
            collect_form_fields(&src, &mut forms);
        });
    }

    let out_dir = src_dir.join("views/generated");
    let _ = fs::create_dir_all(&out_dir);
    let mut body = String::from(
        "/* @generated by namix-build — DO NOT EDIT */\n\
         /* Rust FormField → 同款字段名，供 TSX 表单使用 */\n\n",
    );
    if forms.is_empty() {
        body.push_str("export {}\n");
    } else {
        for (form, fields) in &forms {
            body.push_str(&format!("export const {form} = {{\n"));
            for (variant, field) in fields {
                body.push_str(&format!("  {variant}: \"{field}\" as const,\n"));
            }
            body.push_str("} as const;\n");
            body.push_str(&format!(
                "export type {form}Field = (typeof {form})[keyof typeof {form}];\n\n"
            ));
        }
        body.pop(); // 保留最终换行，避免生成文件末尾的空白行。
    }
    write_if_changed(&out_dir.join("fields.ts"), &body);
}

fn collect_form_fields(src: &str, out: &mut BTreeMap<String, Vec<(String, String)>>) {
    // 粗扫描：`enum LoginForm { ... }` 且附近有 FormField
    let mut rest = src;
    while let Some(idx) = rest.find("enum ") {
        let before = &rest[..idx];
        let has_form_field = before
            .rfind("FormField")
            .is_some_and(|i| before[i..].lines().take(6).any(|l| l.contains("FormField")))
            || before
                .lines()
                .rev()
                .take(12)
                .any(|l| l.contains("FormField"));
        rest = &rest[idx + 5..];
        if !has_form_field {
            continue;
        }
        let Some((name, after_name)) = split_ident(rest) else {
            continue;
        };
        let after_name = after_name.trim_start();
        let Some(body_start) = after_name.find('{') else {
            continue;
        };
        let body = &after_name[body_start + 1..];
        let Some(end) = find_matching_brace(body) else {
            continue;
        };
        let enum_body = &body[..end];
        rest = &body[end + 1..];

        let mut fields = Vec::new();
        for line in enum_body.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') || line.starts_with("//") {
                continue;
            }
            // #[field = "username"]
            if line.contains("field") {
                continue;
            }
            let variant = line.trim_end_matches(',').trim();
            if !is_ident(variant) {
                continue;
            }
            // 回溯上一行 attribute
            let field_name =
                find_prev_field_attr(enum_body, line).unwrap_or_else(|| to_snake_case(variant));
            fields.push((variant.to_string(), field_name));
        }
        if !fields.is_empty() {
            out.insert(name.to_string(), fields);
        }
    }
}

fn find_prev_field_attr(body: &str, variant_line: &str) -> Option<String> {
    let lines: Vec<&str> = body.lines().collect();
    let pos = lines.iter().position(|l| l.trim() == variant_line.trim())?;
    for i in (0..pos).rev() {
        let l = lines[i].trim();
        if l.is_empty() {
            continue;
        }
        if let Some(v) = extract_field_attr(l) {
            return Some(v);
        }
        if !l.starts_with('#') {
            break;
        }
    }
    None
}

fn extract_field_attr(line: &str) -> Option<String> {
    for marker in ["field = \"", "field=\"", "field(\""] {
        if let Some(idx) = line.find(marker) {
            let rest = &line[idx + marker.len()..];
            let end = rest.find('"')?;
            return Some(rest[..end].to_string());
        }
    }
    None
}

fn find_matching_brace(s: &str) -> Option<usize> {
    let mut depth = 0usize;
    for (i, ch) in s.char_indices() {
        match ch {
            '{' => depth += 1,
            '}' => {
                if depth == 0 {
                    return Some(i);
                }
                depth -= 1;
            }
            _ => {}
        }
    }
    None
}

fn to_snake_case(name: &str) -> String {
    let mut out = String::new();
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.extend(ch.to_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

/// 页面注册表：`views/*.{tsx,jsx}` + `#[view]` + `req.view("…")` → `views/generated/registry.ts`
fn generate_view_registry(src_dir: &Path) {
    let mut views: BTreeMap<String, String> = BTreeMap::new();

    // 1) 有 TSX/JSX 就有页面（Laravel 风格 view("login") 的主来源）
    let views_dir = src_dir.join("views");
    if views_dir.is_dir() {
        println!("cargo:rerun-if-changed={}", views_dir.display());
        collect_tsx_views(&views_dir, &mut views);
    }

    // 2) 兼容 ViewProps `#[view("…")]` / 控制器里 `req.view("…")`
    //    单应用：src/controllers；多应用：src/{www,user,admin}/controllers
    let mut controller_dirs: Vec<PathBuf> =
        vec![src_dir.join("controllers"), src_dir.join("pages")];
    for &app in APPS {
        controller_dirs.push(src_dir.join(app).join("controllers"));
    }
    for dir in controller_dirs {
        if !dir.is_dir() {
            continue;
        }
        println!("cargo:rerun-if-changed={}", dir.display());
        visit_rs_files(&dir, &mut |_path, src| {
            let src = strip_rs_comments(src);
            collect_view_attrs(&src, &mut views);
            collect_view_calls(&src, &mut views);
        });
    }

    let out_dir = src_dir.join("views/generated");
    let _ = fs::create_dir_all(&out_dir);
    let mut body = String::from(
        "/* @generated by namix-build — DO NOT EDIT */\n\
         /* views/pages/*.{tsx,jsx} + #[view] / req.view(\"…\") → 页面注册表 */\n\
         import type { ComponentType } from 'react'\n\n",
    );
    // views: name → import path relative to generated/（如 ../pages/login）
    for (name, import_path) in &views {
        let ident = name.replace(['/', '-'], "_");
        body.push_str(&format!(
            "import {ident} from '{import_path}'\n",
            ident = to_pascal_ident(&ident),
        ));
    }
    body.push('\n');
    body.push_str(
        "export const pages: Record<string, ComponentType<Record<string, unknown>>> = {\n",
    );
    for name in views.keys() {
        let ident = to_pascal_ident(&name.replace(['/', '-'], "_"));
        body.push_str(&format!(
            "  '{name}': {ident} as unknown as ComponentType<Record<string, unknown>>,\n"
        ));
        if !name.contains('/') {
            body.push_str(&format!(
                "  '{name}/index': {ident} as unknown as ComponentType<Record<string, unknown>>,\n"
            ));
        }
    }
    body.push_str("}\n");
    write_if_changed(&out_dir.join("registry.ts"), &body);

    write_view_rs(src_dir, &views);

    // Leptos 风格 callRust + #[server] actions 桶
    write_call_rust_ts(&out_dir);
    write_actions_barrel(&out_dir);

    // barrel
    let mut index = String::from("/* @generated by namix-build — DO NOT EDIT */\n");
    index.push_str("export * from './fields'\n");
    index.push_str("export * from './registry'\n");
    index.push_str("export * from './callRust'\n");
    index.push_str("export * as server from './actions'\n");
    // re-export view prop types if present
    if let Ok(entries) = fs::read_dir(&out_dir) {
        for e in entries.flatten() {
            let path = e.path();
            if path.extension().and_then(|x| x.to_str()) != Some("ts") {
                continue;
            }
            let stem = path.file_stem().and_then(|s| s.to_str()).unwrap_or("");
            if matches!(stem, "fields" | "registry" | "index" | "callRust") {
                continue;
            }
            index.push_str(&format!("export * from './{stem}'\n"));
        }
    }
    write_if_changed(&out_dir.join("index.ts"), &index);
}

fn write_call_rust_ts(out_dir: &Path) {
    // 密封协议在 WASM；显式传入 wasm URL，避免默认相对路径打到错误前缀
    let body = r#"/* @generated by namix-build — DO NOT EDIT */
/* callRust → namix-seal WASM（nx_call）。零预备请求，单次 POST /api/a。 */

import wasmUrl from './seal/namix_seal_bg.wasm?url'
import { parseActionFailure } from '../lib/actionError'
import { progress } from '../lib/progress'

type SealMod = {
	default: (input?: { module_or_path?: string | URL | Request | Response | BufferSource | WebAssembly.Module }) => Promise<unknown>
	nx_call: (tok: string, bodyJson: string) => Promise<string>
}

let _seal: Promise<SealMod> | null = null

async function loadSeal(): Promise<SealMod> {
	if (typeof window === 'undefined') {
		throw new Error('callRust 仅在浏览器运行（SPA / Island 客户端）；纯 SSR 勿在服务端调用')
	}
	if (!_seal) {
		_seal = (async () => {
			const mod = (await import('./seal/namix_seal.js')) as SealMod
			// Vite base 与 NAMIX_ASSET_PREFIX/BASE 对齐 → wasmUrl 与 HTML/静态路由一致
			await mod.default({ module_or_path: wasmUrl })
			return mod
		})()
	}
	return _seal
}

/**
 * 统一客户端 → Rust `#[server]` 通道（登录/注册/搜索等一律走这）。
 * `tok` 为混淆动作 token；协议在 WASM 内完成。
 * 失败抛 `ActionException`（含 `errors` 字段袋），供 `useForm` 自动挂载。
 */
export async function callRust<T = Record<string, unknown>>(
	tok: string,
	body?: Record<string, unknown>,
): Promise<T> {
	const seal = await loadSeal()
	progress.start()
	try {
		const raw = await seal.nx_call(tok, JSON.stringify(body ?? {}))
		return JSON.parse(raw) as T
	} catch (err) {
		throw parseActionFailure(err)
	} finally {
		progress.done()
	}
}
"#;
    write_if_changed(&out_dir.join("callRust.ts"), body);
}

fn write_actions_barrel(out_dir: &Path) {
    let actions_dir = out_dir.join("actions");
    let mut body = String::from(
        "/* @generated by namix-build — DO NOT EDIT */\n\
         /* #[server] → import { server } from './generated' ; server.register(...) */\n",
    );
    if actions_dir.is_dir()
        && let Ok(entries) = fs::read_dir(&actions_dir)
    {
        let mut names: Vec<String> = entries
            .flatten()
            .filter_map(|e| {
                let path = e.path();
                if path.extension().and_then(|x| x.to_str()) != Some("ts") {
                    return None;
                }
                let stem = path.file_stem()?.to_str()?.to_string();
                if stem == "index" {
                    return None;
                }
                Some(stem)
            })
            .collect();
        names.sort();
        for name in &names {
            body.push_str(&format!("export {{ {name} }} from './{name}'\n"));
        }
    }
    let _ = fs::create_dir_all(&actions_dir);
    write_if_changed(&actions_dir.join("index.ts"), &body);
}

fn collect_tsx_views(views_dir: &Path, out: &mut BTreeMap<String, String>) {
    // 优先 pages/（业务页，支持 pages/www/home.tsx → view "www/home"）；
    // 根目录仅兼容遗留 views/*.tsx（不递归）
    let pages_dir = views_dir.join("pages");
    if pages_dir.is_dir() {
        collect_tsx_tree(&pages_dir, "pages", "", out);
    }
    collect_tsx_flat_files(views_dir, out);
}

/// 仅收集目录下一层 `*.tsx` / `*.jsx`（遗留布局），不进子目录。
fn collect_tsx_flat_files(dir: &Path, out: &mut BTreeMap<String, String>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_file()
            || !matches!(
                path.extension().and_then(|extension| extension.to_str()),
                Some("tsx" | "jsx")
            )
        {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        if stem.starts_with('_') || stem == "types" {
            continue;
        }
        out.entry(stem.to_string())
            .or_insert_with(|| format!("../{stem}"));
    }
}

/// 递归收集 `pages/**/*.{tsx,jsx}`。
/// `www/home.tsx` → view `"www/home"`，import `../pages/www/home`。
fn collect_tsx_tree(
    dir: &Path,
    import_prefix: &str,
    name_prefix: &str,
    out: &mut BTreeMap<String, String>,
) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        if stem.starts_with('_') {
            continue;
        }
        if path.is_dir() {
            let next_name = if name_prefix.is_empty() {
                stem.to_string()
            } else {
                format!("{name_prefix}/{stem}")
            };
            let next_import = format!("{import_prefix}/{stem}");
            collect_tsx_tree(&path, &next_import, &next_name, out);
            continue;
        }
        if !matches!(
            path.extension().and_then(|e| e.to_str()),
            Some("tsx" | "jsx")
        ) {
            continue;
        }
        let name = if name_prefix.is_empty() {
            stem.to_string()
        } else {
            format!("{name_prefix}/{stem}")
        };
        let import = format!("../{import_prefix}/{stem}");
        out.entry(name).or_insert(import);
    }
}

fn collect_view_attrs(src: &str, out: &mut BTreeMap<String, String>) {
    for marker in ["#[view(\"", "#[view(name = \"", "#[view = \""] {
        let mut rest = src;
        while let Some(idx) = rest.find(marker) {
            rest = &rest[idx + marker.len()..];
            let Some(end) = rest.find('"') else {
                break;
            };
            let name = rest[..end].to_string();
            rest = &rest[end + 1..];
            out.entry(name.clone())
                .or_insert_with(|| format!("../pages/{name}"));
        }
    }
}

/// `req.view("login")` / `.view("login")`
fn collect_view_calls(src: &str, out: &mut BTreeMap<String, String>) {
    for marker in [".view(\"", "view(\""] {
        let mut rest = src;
        while let Some(idx) = rest.find(marker) {
            // 避免把 `preview("` 之类误收：要求 marker 前是标识符边界或 `.`
            if marker == "view(\"" {
                let before = &rest[..idx];
                let prev = before.chars().last();
                if prev.is_some_and(|c| c.is_ascii_alphanumeric() || c == '_') {
                    rest = &rest[idx + marker.len()..];
                    continue;
                }
            }
            rest = &rest[idx + marker.len()..];
            let Some(end) = rest.find('"') else {
                break;
            };
            let name = &rest[..end];
            rest = &rest[end + 1..];
            if !name.is_empty() && !name.starts_with('_') && !name.contains("::") {
                out.entry(name.to_string())
                    .or_insert_with(|| format!("../pages/{name}"));
            }
        }
    }
}

fn to_pascal_ident(s: &str) -> String {
    s.split(['_', '-'])
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut c = p.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect()
}

/// `views/pages/posts.tsx` → `view::posts`；`www/home` → `view::www_home`。
fn view_const_ident(name: &str) -> String {
    let ident = name.replace(['/', '-'], "_");
    if is_rust_keyword(&ident) {
        format!("r#{ident}")
    } else {
        ident
    }
}

fn is_rust_keyword(ident: &str) -> bool {
    matches!(
        ident,
        "as" | "async"
            | "await"
            | "break"
            | "const"
            | "continue"
            | "crate"
            | "dyn"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "abstract"
            | "become"
            | "box"
            | "do"
            | "final"
            | "gen"
            | "macro"
            | "override"
            | "priv"
            | "try"
            | "typeof"
            | "unsized"
            | "virtual"
            | "yield"
    )
}

fn render_view_rs(views: &BTreeMap<String, String>) -> String {
    let mut body = String::from(
        "// @generated by namix-build — DO NOT EDIT\n\
         //! 页面名：`req.view(Page::Posts)` / `req.view(view::posts)` 与 `views/pages/posts.tsx` 对齐。\n\n\
         #![allow(non_upper_case_globals)]\n\n",
    );
    body.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]\n");
    body.push_str("pub enum Page {\n");
    for name in views.keys() {
        body.push_str("    ");
        body.push_str(&view_enum_variant(name));
        body.push_str(",\n");
    }
    body.push_str(
        "}\n\nimpl Page {\n    pub fn as_str(self) -> &'static str {\n        match self {\n",
    );
    for name in views.keys() {
        body.push_str("            Self::");
        body.push_str(&view_enum_variant(name));
        body.push_str(" => ");
        body.push_str(&rust_string_literal(name));
        body.push_str(",\n");
    }
    body.push_str(
        "        }\n    }\n}\n\nimpl From<Page> for String {\n    fn from(page: Page) -> Self {\n        page.as_str().into()\n    }\n}\n\nimpl AsRef<str> for Page {\n    fn as_ref(&self) -> &str {\n        self.as_str()\n    }\n}\n\n",
    );
    if views.is_empty() {
        body.push_str("// （还没有 pages/*.tsx）\n");
    } else {
        for name in views.keys() {
            let ident = view_const_ident(name);
            body.push_str(&format!(
                "pub const {ident}: &str = {};\n",
                rust_string_literal(name)
            ));
        }
    }
    body
}

fn view_enum_variant(name: &str) -> String {
    let ident = view_const_ident(name).trim_start_matches("r#").to_string();
    let pascal = to_pascal_ident(&ident);
    if pascal.is_empty() {
        "Page".into()
    } else if is_rust_keyword(&pascal) || pascal == "Self" {
        format!("P{pascal}")
    } else {
        pascal
    }
}

fn write_view_rs(src_dir: &Path, views: &BTreeMap<String, String>) {
    write_if_changed(&src_dir.join("view.rs"), &render_view_rs(views));
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn temp_case(name: &str) -> PathBuf {
        let nonce = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("clock")
            .as_nanos();
        let root =
            std::env::temp_dir().join(format!("namix-build-{name}-{}-{nonce}", std::process::id()));
        fs::create_dir_all(&root).expect("create test directory");
        root
    }

    #[test]
    fn reads_boolean_feature_table() {
        let root = temp_case("features");
        let config = root.join("namix.toml");
        fs::write(&config, "[features]\npages = true\nmodels = false\n").expect("write config");

        let features = read_features(&config);
        assert_eq!(features.get("pages"), Some(&true));
        assert_eq!(features.get("models"), Some(&false));
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn malformed_config_fails_before_touching_source_files() {
        let root = temp_case("malformed");
        let config = root.join("namix.toml");
        let views = root.join("src/views");
        fs::create_dir_all(&views).expect("create views");
        fs::write(views.join(FEATURE_MARKER), "feature = \"pages\"\n").expect("write marker");
        fs::write(
            views.join("home.tsx"),
            "export default function Home() {}\n",
        )
        .expect("write source");
        fs::write(&config, "[features\npages = false\n").expect("write malformed config");

        let result = std::panic::catch_unwind(|| read_features(&config));
        assert!(result.is_err());
        assert!(views.join("home.tsx").is_file());
        assert!(views.join(FEATURE_MARKER).is_file());
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn non_boolean_feature_is_rejected() {
        let root = temp_case("feature-type");
        let config = root.join("namix.toml");
        fs::write(&config, "[features]\npages = \"yes\"\n").expect("write config");

        assert!(std::panic::catch_unwind(|| read_features(&config)).is_err());
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn view_registry_collects_tsx_and_jsx_pages() {
        let root = temp_case("view-languages");
        let src = root.join("src");
        let pages = src.join("views/pages");
        let nested = pages.join("admin");
        fs::create_dir_all(&nested).expect("create page directories");
        fs::write(
            pages.join("home.jsx"),
            "export default function Home() { return null }\n",
        )
        .expect("write jsx page");
        fs::write(
            nested.join("dashboard.tsx"),
            "export default function Dashboard() { return null }\n",
        )
        .expect("write tsx page");

        generate_view_registry(&src);

        let registry =
            fs::read_to_string(src.join("views/generated/registry.ts")).expect("read registry");
        assert!(registry.contains("import Home from '../pages/home'"));
        assert!(registry.contains("import AdminDashboard from '../pages/admin/dashboard'"));
        assert!(
            registry.contains("'home': Home as unknown as ComponentType<Record<string, unknown>>")
        );
        assert!(registry.contains("'admin/dashboard': AdminDashboard"));

        let view_rs = fs::read_to_string(src.join("view.rs")).expect("read view.rs");
        assert!(view_rs.contains("pub const home: &str = \"home\";"));
        assert!(view_rs.contains("pub const admin_dashboard: &str = \"admin/dashboard\";"));
        assert!(view_rs.contains("pub enum Page"));
        assert!(view_rs.contains("Home,"));
        assert!(view_rs.contains("AdminDashboard,"));
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn view_const_idents_sanitize_paths_and_keywords() {
        assert_eq!(view_const_ident("posts"), "posts");
        assert_eq!(view_const_ident("www/home"), "www_home");
        assert_eq!(view_const_ident("type"), "r#type");
        let rendered = render_view_rs(&BTreeMap::from([
            ("login".into(), "../pages/login".into()),
            ("type".into(), "../pages/type".into()),
        ]));
        assert!(rendered.contains("pub const login: &str = \"login\";"));
        assert!(rendered.contains("pub const r#type: &str = \"type\";"));
        assert!(rendered.contains("pub enum Page"));
        assert!(rendered.contains("Self::Login => \"login\""));
        assert!(rendered.contains("Self::Type => \"type\""));
    }

    #[test]
    fn empty_views_still_emit_page_enum() {
        let rendered = render_view_rs(&BTreeMap::new());
        assert!(rendered.contains("pub enum Page {"));
        assert!(rendered.contains("match self {"));
        assert!(!rendered.contains("pub const"));
    }

    #[test]
    fn dsl_route_uris_bind_the_nearest_name() {
        let src = r#"
            GET "/" => home::index, name: "home",
            GET "/login" => auth::login, name: "login",
                middleware = [require_guest],
            GET "/profile/:id" => profile::show, name: "profile",
            POST "/posts/:id" => posts::update, name: "posts.update",
        "#;
        let mut uris = BTreeMap::new();
        collect_dsl_route_uris(src, &mut uris);
        assert_eq!(uris.get("home").map(String::as_str), Some("/"));
        assert_eq!(uris.get("login").map(String::as_str), Some("/login"));
        assert_eq!(
            uris.get("profile").map(String::as_str),
            Some("/profile/:id")
        );
        assert_eq!(
            uris.get("posts.update").map(String::as_str),
            Some("/posts/:id")
        );
    }
}
