//! 供业务包 `build.rs` 调用。
//!
//! ThinkPHP 风格多应用目录：
//! ```text
//! src/common/{services,models,middleware,events,listeners}
//! src/common/{validators,requests}  # namix.toml [features] 开关
//! src/views/                       # pages=true → TSX（非 Rust mod）
//! src/www|user|admin/{controllers,routes,middleware}
//! ```

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

/// 业务应用名（可按项目扩展）。
pub const APPS: &[&str] = &["www", "user", "admin"];

const APP_CORE_DIRS: &[&str] = &["controllers", "middleware", "routes"];
const COMMON_CORE_DIRS: &[&str] = &[
    "middleware",
    "services",
    "models",
    "events",
    "listeners",
    "seeders",
];
/// `(namix.toml [features] 键, 目录名)` — 关闭时删除带 `.namix-feature` 的目录。
const FEATURE_DIRS: &[(&str, &str)] = &[("validators", "validators"), ("requests", "requests")];
const FEATURE_MARKER: &str = ".namix-feature";

/// 单应用同步：扁平 `src/{controllers,routes,middleware,services,models,...}`。
///
/// ```text
/// src/
///   controllers/ routes/ middleware/
///   services/ models/ events/ listeners/ seeders/   # 核心（始终）
///   validators/ requests/ pages/                   # [features] 开关
/// ```
pub fn sync_single() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let src_dir = manifest_dir.join("src");
    let config_path = manifest_dir.join("namix.toml");

    println!("cargo:rerun-if-changed={}", config_path.display());
    let features = read_features(&config_path);

    const CORE: &[&str] = &[
        "controllers",
        "middleware",
        "routes",
        "services",
        "models",
        "events",
        "listeners",
        "seeders",
    ];
    const FEATURES: &[(&str, &str)] = &[("validators", "validators"), ("requests", "requests")];

    for &dir_name in CORE {
        let dir = src_dir.join(dir_name);
        ensure_dir(&dir);
        watch_dir(&dir);
        generate_mod_rs(&dir);
    }

    let mut active: Vec<&str> = CORE.to_vec();
    for &(feature, dir_name) in FEATURES {
        let dir = src_dir.join(dir_name);
        if features.get(feature).copied().unwrap_or(false) {
            ensure_feature_dir(&dir, feature);
            active.push(dir_name);
        } else {
            remove_feature_dir(&dir);
        }
        watch_dir(&dir);
        if dir.is_dir() {
            generate_mod_rs(&dir);
        }
    }

    // pages feature → TSX `views/`；页面契约写在 `controllers/`（与 handler 同文件）
    let views = src_dir.join("views");
    let pages = src_dir.join("pages");
    let legacy_props = src_dir.join("props");
    if features.get("pages").copied().unwrap_or(false) {
        ensure_feature_dir(&views, "pages");
        watch_dir(&views);
        // 可选遗留目录：仍支持单独 pages/，但不再强制创建
        if legacy_props.is_dir() && !pages.is_dir() {
            let _ = fs::rename(&legacy_props, &pages);
        }
        if pages.is_dir() {
            watch_dir(&pages);
            generate_pages_mod_rs(&pages);
            if !active.contains(&"pages") {
                active.push("pages");
            }
        }
        generate_frontend_fields(&src_dir);
        generate_view_registry(&src_dir);
    } else {
        remove_feature_dir(&views);
        remove_feature_dir(&pages);
        remove_feature_dir(&legacy_props);
    }

    let mut body = String::from("// @generated by namix-build — DO NOT EDIT\n\n");
    for name in &active {
        body.push_str("pub mod ");
        body.push_str(name);
        body.push_str(";\n");
    }
    write_if_changed(&src_dir.join("namix_modules.rs"), &body);
    generate_route_names(&src_dir);
}

/// 多应用同步：一份代码，common 复用，各端只写自己的控制器/路由。
pub fn sync() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let src_dir = manifest_dir.join("src");
    let config_path = manifest_dir.join("namix.toml");

    println!("cargo:rerun-if-changed={}", config_path.display());
    let features = read_features(&config_path);

    // common
    let common = src_dir.join("common");
    ensure_dir(&common);
    for &dir_name in COMMON_CORE_DIRS {
        let dir = common.join(dir_name);
        ensure_dir(&dir);
        watch_dir(&dir);
        generate_mod_rs(&dir);
    }
    for &(feature, dir_name) in FEATURE_DIRS {
        let dir = common.join(dir_name);
        if features.get(feature).copied().unwrap_or(false) {
            ensure_feature_dir(&dir, feature);
        } else {
            remove_feature_dir(&dir);
        }
        watch_dir(&dir);
        if dir.is_dir() {
            generate_mod_rs(&dir);
        }
    }
    let mut common_mods: Vec<&str> = COMMON_CORE_DIRS.to_vec();
    for &(feature, dir_name) in FEATURE_DIRS {
        if features.get(feature).copied().unwrap_or(false) {
            common_mods.push(dir_name);
        }
    }
    generate_package_mod(&common, &common_mods);
    watch_dir(&common);

    // pages → 根级 TSX `src/views/`（非 Rust mod）
    let views = src_dir.join("views");
    if features.get("pages").copied().unwrap_or(false) {
        ensure_feature_dir(&views, "pages");
        watch_dir(&views);
        remove_feature_dir(&common.join("pages"));
    } else {
        remove_feature_dir(&views);
        remove_feature_dir(&common.join("pages"));
    }

    // 各端应用：controllers/routes/middleware 始终；
    // validators 仅在目录已存在时挂上（nx make validator --app user）
    for &app in APPS {
        let app_dir = src_dir.join(app);
        ensure_dir(&app_dir);
        let mut children: Vec<&str> = APP_CORE_DIRS.to_vec();
        for &dir_name in APP_CORE_DIRS {
            let dir = app_dir.join(dir_name);
            ensure_dir(&dir);
            watch_dir(&dir);
            generate_mod_rs(&dir);
        }
        let app_validators = app_dir.join("validators");
        if app_validators.is_dir() {
            watch_dir(&app_validators);
            generate_mod_rs(&app_validators);
            children.push("validators");
        }
        generate_package_mod(&app_dir, &children);
        watch_dir(&app_dir);
    }

    generate_route_names(&src_dir);
}

fn read_features(path: &Path) -> BTreeMap<String, bool> {
    let Ok(raw) = fs::read_to_string(path) else {
        return BTreeMap::new();
    };
    let Ok(value) = toml::from_str::<toml::Value>(&raw) else {
        return BTreeMap::new();
    };
    let mut map = BTreeMap::new();
    if let Some(table) = value.get("features").and_then(|v| v.as_table()) {
        for (k, v) in table {
            map.insert(k.clone(), v.as_bool().unwrap_or(false));
        }
    }
    map
}

fn ensure_dir(dir: &Path) {
    if !dir.exists() {
        fs::create_dir_all(dir).expect("创建目录失败");
    }
}

fn ensure_feature_dir(dir: &Path, feature: &str) {
    ensure_dir(dir);
    let marker = dir.join(FEATURE_MARKER);
    if !marker.exists() {
        fs::write(
            &marker,
            format!("feature = \"{feature}\"\n# managed by namix-build — do not remove\n"),
        )
        .expect("写入 feature 标记失败");
    }
}

fn remove_feature_dir(dir: &Path) {
    if !dir.exists() {
        return;
    }
    let marker = dir.join(FEATURE_MARKER);
    if !marker.exists() {
        println!(
            "cargo:warning=跳过删除 {}（缺少 {FEATURE_MARKER}）",
            dir.display()
        );
        return;
    }
    fs::remove_dir_all(dir).unwrap_or_else(|e| panic!("删除失败 {}: {e}", dir.display()));
}

fn watch_dir(dir: &Path) {
    if dir.is_dir() {
        println!("cargo:rerun-if-changed={}", dir.display());
    }
}

fn generate_mod_rs(dir: &Path) {
    if !dir.is_dir() {
        return;
    }
    let modules = list_rs_modules(dir);
    let mut body = String::from(
        "// @generated by namix-build — DO NOT EDIT\n\
         // 新增 .rs 后 cargo check 自动注册。\n\n",
    );
    for name in &modules {
        body.push_str("pub mod ");
        body.push_str(name);
        body.push_str(";\n");
    }
    write_if_changed(&dir.join("mod.rs"), &body);
}

/// `pages/`：页面契约（数据形状 + 渲染模式）。`Demo::new(..).render(&req)`。
fn generate_pages_mod_rs(dir: &Path) {
    if !dir.is_dir() {
        return;
    }
    let modules = list_rs_modules(dir);
    let mut body = String::from(
        "// @generated by namix-build — DO NOT EDIT\n\
         // 新增 .rs 后 cargo check 自动注册；扁平导出页面类型。\n\n",
    );
    for name in &modules {
        body.push_str("pub mod ");
        body.push_str(name);
        body.push_str(";\n");
    }
    if !modules.is_empty() {
        body.push('\n');
        for name in &modules {
            let ty = to_pascal_ident(name);
            body.push_str(&format!("pub use {name}::{ty};\n"));
        }
    }
    write_if_changed(&dir.join("mod.rs"), &body);
}

fn list_rs_modules(dir: &Path) -> Vec<String> {
    let mut modules = Vec::new();
    for entry in fs::read_dir(dir).expect("读取目录失败").flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("rs") {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        if stem == "mod" {
            continue;
        }
        modules.push(stem.to_string());
    }
    modules.sort();
    modules
}

fn generate_package_mod(dir: &Path, children: &[&str]) {
    let mut body = String::from("// @generated by namix-build — DO NOT EDIT\n\n");
    for name in children {
        body.push_str("pub mod ");
        body.push_str(name);
        body.push_str(";\n");
    }
    write_if_changed(&dir.join("mod.rs"), &body);
}

fn write_if_changed(path: &Path, content: &str) {
    if fs::read_to_string(path).ok().as_deref() == Some(content) {
        return;
    }
    fs::write(path, content).unwrap_or_else(|e| panic!("写入 {} 失败: {e}", path.display()));
}

/// 从各应用 `routes/**/*.rs` 扫描命名路由，生成类型化 `route::user::login`。
///
/// 从 `routes/**/*.rs` 收集命名路由 → `OUT_DIR/namix_route_names.rs`。
///
/// 注册处写短字符串 `.name("login")`；使用处 `route::main::login`（类型补全）。
fn generate_route_names(src_dir: &Path) {
    // app → (leaf_ident → route_name_string)
    let mut apps: BTreeMap<String, BTreeMap<String, String>> = BTreeMap::new();

    for &app in APPS {
        let routes_dir = src_dir.join(app).join("routes");
        if routes_dir.is_dir() {
            println!("cargo:rerun-if-changed={}", routes_dir.display());
            visit_rs_files(&routes_dir, &mut |_path, src| {
                let src = strip_rs_comments(src);
                collect_route_path_names(&src, &mut apps);
                collect_string_route_names(&src, &mut apps);
            });
        }
    }
    let single_routes = src_dir.join("routes");
    if single_routes.is_dir() {
        println!("cargo:rerun-if-changed={}", single_routes.display());
        visit_rs_files(&single_routes, &mut |_path, src| {
            let src = strip_rs_comments(src);
            collect_route_path_names(&src, &mut apps);
            collect_string_route_names(&src, &mut apps);
        });
    }

    let mut body = String::from(
        "// @generated by namix-build — DO NOT EDIT\n\
         // 来源：routes 里 name: \"login\" / .name(\"login.submit\") 或 route::main::login\n\
         // 注册用短字符串；使用处 route::main::*（leaf 的 _ → 默认名里的 .）\n\n",
    );

    if apps.is_empty() {
        body.push_str("// （routes 里还没有命名路由）\n");
    } else {
        body.push_str("namix::route_names! {\n");
        for (app, leaves) in &apps {
            body.push_str("    ");
            body.push_str(app);
            body.push_str(" {\n");
            for (leaf, route_str) in leaves {
                let default = format!("{app}.{}", leaf.replace('_', "."));
                body.push_str("        ");
                if *route_str == default {
                    body.push_str(leaf);
                    body.push_str(",\n");
                } else {
                    body.push_str(&format!("{leaf} = \"{route_str}\",\n"));
                }
            }
            body.push_str("    }\n");
        }
        body.push_str("}\n");
    }

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    write_if_changed(&out_dir.join("namix_route_names.rs"), &body);
}

/// 去掉 `//` / `///` / `/* */`，避免注释里的示例污染路由表。
fn strip_rs_comments(src: &str) -> String {
    let mut out = String::with_capacity(src.len());
    let mut chars = src.chars().peekable();
    let mut in_block = false;
    let mut in_string = false;
    while let Some(c) = chars.next() {
        if in_block {
            if c == '*' && chars.peek() == Some(&'/') {
                chars.next();
                in_block = false;
            }
            continue;
        }
        if in_string {
            out.push(c);
            if c == '\\' {
                if let Some(n) = chars.next() {
                    out.push(n);
                }
            } else if c == '"' {
                in_string = false;
            }
            continue;
        }
        match c {
            '"' => {
                in_string = true;
                out.push(c);
            }
            '/' if chars.peek() == Some(&'/') => {
                chars.next();
                for n in chars.by_ref() {
                    if n == '\n' {
                        out.push('\n');
                        break;
                    }
                }
            }
            '/' if chars.peek() == Some(&'*') => {
                chars.next();
                in_block = true;
            }
            _ => out.push(c),
        }
    }
    out
}

fn visit_rs_files(dir: &Path, f: &mut dyn FnMut(&Path, &str)) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            visit_rs_files(&path, f);
        } else if path.extension().and_then(|e| e.to_str()) == Some("rs")
            && let Ok(src) = fs::read_to_string(&path)
        {
            f(&path, &src);
        }
    }
}

fn collect_route_path_names(src: &str, apps: &mut BTreeMap<String, BTreeMap<String, String>>) {
    let mut rest = src;
    while let Some(idx) = rest.find("route::") {
        let before = &rest[..idx];
        let prev = before.chars().last();
        if prev.is_some_and(|c| c.is_ascii_alphanumeric() || c == '_') {
            rest = &rest[idx + 7..];
            continue;
        }
        rest = &rest[idx + 7..];
        if let Some((app, leaf)) = parse_route_path_tail(rest)
            && is_ident(&app)
            && is_ident(&leaf)
        {
            let default = format!("{app}.{}", leaf.replace('_', "."));
            apps.entry(app).or_default().entry(leaf).or_insert(default);
        }
    }
}

/// `user::login` / `user::register_submit`（恰好两段）
fn parse_route_path_tail(s: &str) -> Option<(String, String)> {
    let (app, after_app) = split_ident(s)?;
    if !after_app.starts_with("::") {
        return None;
    }
    let (leaf, _) = split_ident(&after_app[2..])?;
    Some((app.to_string(), leaf.to_string()))
}

fn split_ident(s: &str) -> Option<(&str, &str)> {
    let mut end = 0;
    for (i, c) in s.char_indices() {
        if i == 0 {
            if !(c.is_ascii_alphabetic() || c == '_') {
                return None;
            }
        } else if !(c.is_ascii_alphanumeric() || c == '_') {
            end = i;
            break;
        }
        end = i + c.len_utf8();
    }
    if end == 0 {
        return None;
    }
    Some((&s[..end], &s[end..]))
}

fn is_ident(s: &str) -> bool {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' => {}
        _ => return false,
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn collect_string_route_names(src: &str, apps: &mut BTreeMap<String, BTreeMap<String, String>>) {
    for marker in [".name(\"", "name: \"", "name = \""] {
        let mut rest = src;
        while let Some(idx) = rest.find(marker) {
            rest = &rest[idx + marker.len()..];
            let Some(end) = rest.find('"') else {
                break;
            };
            let name = &rest[..end];
            rest = &rest[end + 1..];
            insert_dotted_route_name(name, apps);
        }
    }
}

/// `.name("login")` / `.name("login.submit")` → `main::{login|login_submit}`，路由名保持原串。
fn insert_dotted_route_name(name: &str, apps: &mut BTreeMap<String, BTreeMap<String, String>>) {
    if name.starts_with("__") {
        return;
    }
    let parts: Vec<&str> = name.split('.').filter(|p| !p.is_empty()).collect();
    if parts.is_empty() || !parts.iter().all(|p| is_ident(p)) {
        return;
    }
    let leaf = parts.join("_");
    apps.entry("main".into())
        .or_default()
        .insert(leaf, name.to_string());
}
/// 扫描 `validators/**/*.rs` 的 FormField enum → `views/generated/fields.ts`
fn generate_frontend_fields(src_dir: &Path) {
    let mut forms: BTreeMap<String, Vec<(String, String)>> = BTreeMap::new();
    for dir_name in ["validators", "common/validators"] {
        let dir = src_dir.join(dir_name);
        if !dir.is_dir() {
            continue;
        }
        println!("cargo:rerun-if-changed={}", dir.display());
        visit_rs_files(&dir, &mut |_path, src| {
            let src = strip_rs_comments(src);
            collect_form_fields(&src, &mut forms);
        });
    }

    let out_dir = src_dir.join("views/generated");
    let _ = fs::create_dir_all(&out_dir);
    let mut body = String::from(
        "/* @generated by namix-build — DO NOT EDIT */\n\
         /* Rust FormField → 同款字段名，供 TSX 表单使用 */\n\n",
    );
    if forms.is_empty() {
        body.push_str("export {}\n");
    } else {
        for (form, fields) in &forms {
            body.push_str(&format!("export const {form} = {{\n"));
            for (variant, field) in fields {
                body.push_str(&format!("  {variant}: \"{field}\" as const,\n"));
            }
            body.push_str("} as const;\n");
            body.push_str(&format!(
                "export type {form}Field = (typeof {form})[keyof typeof {form}];\n\n"
            ));
        }
        body.pop(); // 保留最终换行，避免生成文件末尾的空白行。
    }
    write_if_changed(&out_dir.join("fields.ts"), &body);
}

fn collect_form_fields(src: &str, out: &mut BTreeMap<String, Vec<(String, String)>>) {
    // 粗扫描：`enum LoginForm { ... }` 且附近有 FormField
    let mut rest = src;
    while let Some(idx) = rest.find("enum ") {
        let before = &rest[..idx];
        let has_form_field = before
            .rfind("FormField")
            .is_some_and(|i| before[i..].lines().take(6).any(|l| l.contains("FormField")))
            || before
                .lines()
                .rev()
                .take(12)
                .any(|l| l.contains("FormField"));
        rest = &rest[idx + 5..];
        if !has_form_field {
            continue;
        }
        let Some((name, after_name)) = split_ident(rest) else {
            continue;
        };
        let after_name = after_name.trim_start();
        let Some(body_start) = after_name.find('{') else {
            continue;
        };
        let body = &after_name[body_start + 1..];
        let Some(end) = find_matching_brace(body) else {
            continue;
        };
        let enum_body = &body[..end];
        rest = &body[end + 1..];

        let mut fields = Vec::new();
        for line in enum_body.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') || line.starts_with("//") {
                continue;
            }
            // #[field = "username"]
            if line.contains("field") {
                continue;
            }
            let variant = line.trim_end_matches(',').trim();
            if !is_ident(variant) {
                continue;
            }
            // 回溯上一行 attribute
            let field_name =
                find_prev_field_attr(enum_body, line).unwrap_or_else(|| to_snake_case(variant));
            fields.push((variant.to_string(), field_name));
        }
        if !fields.is_empty() {
            out.insert(name.to_string(), fields);
        }
    }
}

fn find_prev_field_attr(body: &str, variant_line: &str) -> Option<String> {
    let lines: Vec<&str> = body.lines().collect();
    let pos = lines.iter().position(|l| l.trim() == variant_line.trim())?;
    for i in (0..pos).rev() {
        let l = lines[i].trim();
        if l.is_empty() {
            continue;
        }
        if let Some(v) = extract_field_attr(l) {
            return Some(v);
        }
        if !l.starts_with('#') {
            break;
        }
    }
    None
}

fn extract_field_attr(line: &str) -> Option<String> {
    for marker in ["field = \"", "field=\"", "field(\""] {
        if let Some(idx) = line.find(marker) {
            let rest = &line[idx + marker.len()..];
            let end = rest.find('"')?;
            return Some(rest[..end].to_string());
        }
    }
    None
}

fn find_matching_brace(s: &str) -> Option<usize> {
    let mut depth = 0usize;
    for (i, ch) in s.char_indices() {
        match ch {
            '{' => depth += 1,
            '}' => {
                if depth == 0 {
                    return Some(i);
                }
                depth -= 1;
            }
            _ => {}
        }
    }
    None
}

fn to_snake_case(name: &str) -> String {
    let mut out = String::new();
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.extend(ch.to_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

/// 页面注册表：`views/*.tsx` + `#[view]` + `req.view("…")` → `views/generated/registry.ts`
fn generate_view_registry(src_dir: &Path) {
    let mut views: BTreeMap<String, String> = BTreeMap::new();

    // 1) 有 TSX 就有页面（Laravel 风格 view("login") 的主来源）
    let views_dir = src_dir.join("views");
    if views_dir.is_dir() {
        println!("cargo:rerun-if-changed={}", views_dir.display());
        collect_tsx_views(&views_dir, &mut views);
    }

    // 2) 兼容 ViewProps `#[view("…")]` / 控制器里 `req.view("…")`
    for dir_name in ["controllers", "pages"] {
        let dir = src_dir.join(dir_name);
        if !dir.is_dir() {
            continue;
        }
        println!("cargo:rerun-if-changed={}", dir.display());
        visit_rs_files(&dir, &mut |_path, src| {
            let src = strip_rs_comments(src);
            collect_view_attrs(&src, &mut views);
            collect_view_calls(&src, &mut views);
        });
    }

    let out_dir = src_dir.join("views/generated");
    let _ = fs::create_dir_all(&out_dir);
    let mut body = String::from(
        "/* @generated by namix-build — DO NOT EDIT */\n\
         /* views/pages/*.tsx + #[view] / req.view(\"…\") → 页面注册表 */\n\
         import type { ComponentType } from 'react'\n\n",
    );
    // views: name → import path relative to generated/（如 ../pages/login）
    for (name, import_path) in &views {
        let ident = name.replace(['/', '-'], "_");
        body.push_str(&format!(
            "import {ident} from '{import_path}'\n",
            ident = to_pascal_ident(&ident),
        ));
    }
    body.push('\n');
    body.push_str(
        "export const pages: Record<string, ComponentType<Record<string, unknown>>> = {\n",
    );
    for name in views.keys() {
        let ident = to_pascal_ident(&name.replace(['/', '-'], "_"));
        body.push_str(&format!(
            "  '{name}': {ident} as ComponentType<Record<string, unknown>>,\n"
        ));
        if !name.contains('/') {
            body.push_str(&format!(
                "  '{name}/index': {ident} as ComponentType<Record<string, unknown>>,\n"
            ));
        }
    }
    body.push_str("}\n");
    write_if_changed(&out_dir.join("registry.ts"), &body);

    // Leptos 风格 callRust + #[server] actions 桶
    write_call_rust_ts(&out_dir);
    write_actions_barrel(&out_dir);

    // barrel
    let mut index = String::from("/* @generated by namix-build — DO NOT EDIT */\n");
    index.push_str("export * from './fields'\n");
    index.push_str("export * from './registry'\n");
    index.push_str("export * from './callRust'\n");
    index.push_str("export * as server from './actions'\n");
    // re-export view prop types if present
    if let Ok(entries) = fs::read_dir(&out_dir) {
        for e in entries.flatten() {
            let path = e.path();
            if path.extension().and_then(|x| x.to_str()) != Some("ts") {
                continue;
            }
            let stem = path.file_stem().and_then(|s| s.to_str()).unwrap_or("");
            if matches!(stem, "fields" | "registry" | "index" | "callRust") {
                continue;
            }
            index.push_str(&format!("export * from './{stem}'\n"));
        }
    }
    write_if_changed(&out_dir.join("index.ts"), &index);
}

fn write_call_rust_ts(out_dir: &Path) {
    // 密封协议在 WASM；显式传入 wasm URL，避免默认相对路径打到错误前缀
    let body = r#"/* @generated by namix-build — DO NOT EDIT */
/* callRust → namix-seal WASM（nx_call）。零预备请求，单次 POST /api/a。 */

import wasmUrl from './seal/namix_seal_bg.wasm?url'
import { parseActionFailure } from '../lib/actionError'
import { progress } from '../lib/progress'

type SealMod = {
	default: (input?: { module_or_path?: string | URL | Request | Response | BufferSource | WebAssembly.Module }) => Promise<unknown>
	nx_call: (tok: string, bodyJson: string) => Promise<string>
}

let _seal: Promise<SealMod> | null = null

async function loadSeal(): Promise<SealMod> {
	if (typeof window === 'undefined') {
		throw new Error('callRust 仅在浏览器运行（SPA / Island 客户端）；纯 SSR 勿在服务端调用')
	}
	if (!_seal) {
		_seal = (async () => {
			const mod = (await import('./seal/namix_seal.js')) as SealMod
			// Vite base=/build/ → wasmUrl 为 /build/assets/….wasm（与 Namix 静态路由一致）
			await mod.default({ module_or_path: wasmUrl })
			return mod
		})()
	}
	return _seal
}

/**
 * 统一客户端 → Rust `#[server]` 通道（登录/注册/搜索等一律走这）。
 * `tok` 为混淆动作 token；协议在 WASM 内完成。
 * 失败抛 `ActionException`（含 `errors` 字段袋），供 `useForm` 自动挂载。
 */
export async function callRust<T = Record<string, unknown>>(
	tok: string,
	body?: Record<string, unknown>,
): Promise<T> {
	const seal = await loadSeal()
	progress.start()
	try {
		const raw = await seal.nx_call(tok, JSON.stringify(body ?? {}))
		return JSON.parse(raw) as T
	} catch (err) {
		throw parseActionFailure(err)
	} finally {
		progress.done()
	}
}
"#;
    write_if_changed(&out_dir.join("callRust.ts"), body);
}

fn write_actions_barrel(out_dir: &Path) {
    let actions_dir = out_dir.join("actions");
    let mut body = String::from(
        "/* @generated by namix-build — DO NOT EDIT */\n\
         /* #[server] → import { server } from './generated' ; server.register(...) */\n",
    );
    if actions_dir.is_dir()
        && let Ok(entries) = fs::read_dir(&actions_dir)
    {
        let mut names: Vec<String> = entries
            .flatten()
            .filter_map(|e| {
                let path = e.path();
                if path.extension().and_then(|x| x.to_str()) != Some("ts") {
                    return None;
                }
                let stem = path.file_stem()?.to_str()?.to_string();
                if stem == "index" {
                    return None;
                }
                Some(stem)
            })
            .collect();
        names.sort();
        for name in &names {
            body.push_str(&format!("export {{ {name} }} from './{name}'\n"));
        }
    }
    let _ = fs::create_dir_all(&actions_dir);
    write_if_changed(&actions_dir.join("index.ts"), &body);
}

fn collect_tsx_views(views_dir: &Path, out: &mut BTreeMap<String, String>) {
    // 优先 pages/（业务页）；根目录仅兼容遗留 *.tsx
    let pages_dir = views_dir.join("pages");
    if pages_dir.is_dir() {
        collect_tsx_in_dir(&pages_dir, "pages", out);
    }
    collect_tsx_in_dir(views_dir, "", out);
}

/// `out`: view 名 → 相对 `generated/` 的 import 路径
fn collect_tsx_in_dir(dir: &Path, prefix: &str, out: &mut BTreeMap<String, String>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        if path.extension().and_then(|e| e.to_str()) != Some("tsx") {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        // 跳过框架入口 / 私有文件 / 组件目录误扫
        if stem.starts_with('_') || stem == "types" {
            continue;
        }
        let import = if prefix.is_empty() {
            format!("../{stem}")
        } else {
            format!("../{prefix}/{stem}")
        };
        // pages/ 优先；根目录不覆盖已有
        out.entry(stem.to_string()).or_insert(import);
    }
}

fn collect_view_attrs(src: &str, out: &mut BTreeMap<String, String>) {
    for marker in ["#[view(\"", "#[view(name = \"", "#[view = \""] {
        let mut rest = src;
        while let Some(idx) = rest.find(marker) {
            rest = &rest[idx + marker.len()..];
            let Some(end) = rest.find('"') else {
                break;
            };
            let name = rest[..end].to_string();
            rest = &rest[end + 1..];
            out.entry(name.clone())
                .or_insert_with(|| format!("../pages/{name}"));
        }
    }
}

/// `req.view("login")` / `.view("login")`
fn collect_view_calls(src: &str, out: &mut BTreeMap<String, String>) {
    for marker in [".view(\"", "view(\""] {
        let mut rest = src;
        while let Some(idx) = rest.find(marker) {
            // 避免把 `preview("` 之类误收：要求 marker 前是标识符边界或 `.`
            if marker == "view(\"" {
                let before = &rest[..idx];
                let prev = before.chars().last();
                if prev.is_some_and(|c| c.is_ascii_alphanumeric() || c == '_') {
                    rest = &rest[idx + marker.len()..];
                    continue;
                }
            }
            rest = &rest[idx + marker.len()..];
            let Some(end) = rest.find('"') else {
                break;
            };
            let name = &rest[..end];
            rest = &rest[end + 1..];
            if !name.is_empty() && !name.starts_with('_') && !name.contains("::") {
                out.entry(name.to_string())
                    .or_insert_with(|| format!("../pages/{name}"));
            }
        }
    }
}

fn to_pascal_ident(s: &str) -> String {
    s.split(['_', '-'])
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut c = p.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect()
}
