// @generated by namix-build — DO NOT EDIT
//! 页面名：`req.view(Page::Posts)` / `req.view(view::posts)` 与 `views/pages/posts.tsx` 对齐。

#![allow(non_upper_case_globals)]

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Page {
    AdminUsers,
    Chat,
    Demo,
    EmailVerify,
    Errors,
    Home,
    Island,
    Login,
    Mailbox,
    Me,
    Posts,
    Profile,
    Register,
}

impl Page {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::AdminUsers => "admin_users",
            Self::Chat => "chat",
            Self::Demo => "demo",
            Self::EmailVerify => "email_verify",
            Self::Errors => "errors",
            Self::Home => "home",
            Self::Island => "island",
            Self::Login => "login",
            Self::Mailbox => "mailbox",
            Self::Me => "me",
            Self::Posts => "posts",
            Self::Profile => "profile",
            Self::Register => "register",
        }
    }
}

impl From<Page> for String {
    fn from(page: Page) -> Self {
        page.as_str().into()
    }
}

impl AsRef<str> for Page {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

pub const admin_users: &str = "admin_users";
pub const chat: &str = "chat";
pub const demo: &str = "demo";
pub const email_verify: &str = "email_verify";
pub const errors: &str = "errors";
pub const home: &str = "home";
pub const island: &str = "island";
pub const login: &str = "login";
pub const mailbox: &str = "mailbox";
pub const me: &str = "me";
pub const posts: &str = "posts";
pub const profile: &str = "profile";
pub const register: &str = "register";
