use std::collections::BTreeMap;
use std::collections::HashMap;
use std::fs;
use std::path::Path;

use serde::Serialize;

/// 命名路由表：`name → /path/:param`（可导出给前端）。
#[derive(Clone, Debug, Default)]
pub struct RouteCatalog {
    /// name → uri pattern
    names: HashMap<String, String>,
    /// name → HTTP methods（同一 name 多方法时合并）
    methods: HashMap<String, Vec<String>>,
}

/// 单条命名路由（Ziggy 风格，供前端 `route('user.profile', {id})`）。
#[derive(Clone, Debug, Serialize)]
pub struct RouteExport {
    pub uri: String,
    pub methods: Vec<String>,
}

impl RouteCatalog {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn insert(&mut self, name: impl Into<String>, path: impl Into<String>) {
        self.insert_with_method(name, path, None);
    }

    pub fn insert_with_method(
        &mut self,
        name: impl Into<String>,
        path: impl Into<String>,
        method: Option<&str>,
    ) {
        let name = name.into();
        let path = path.into();
        if let Some(existing) = self.names.get(&name) {
            assert_eq!(
                existing, &path,
                "named route `{name}` is registered with conflicting URIs: `{existing}` and `{path}`"
            );
        } else {
            self.names.insert(name.clone(), path);
        }
        if let Some(m) = method {
            let list = self.methods.entry(name).or_default();
            let m = m.to_ascii_uppercase();
            if !list.iter().any(|x| x == &m) {
                list.push(m);
            }
        }
    }

    pub fn path(&self, name: &str) -> Option<&str> {
        self.names.get(name).map(String::as_str)
    }

    /// 用参数填充 `:id` / `*path` 等占位符。
    pub fn url(&self, name: &str, params: &[(&str, &str)]) -> Option<String> {
        let mut out = self.path(name)?.to_string();
        for (key, value) in params {
            for token in [format!(":{key}"), format!("*{key}")] {
                if out.contains(&token) {
                    out = out.replace(&token, value);
                }
            }
        }
        if has_unfilled_param(&out) {
            return None;
        }
        Some(out)
    }

    pub fn names(&self) -> impl Iterator<Item = (&str, &str)> {
        self.names.iter().map(|(k, v)| (k.as_str(), v.as_str()))
    }

    /// 导出为有序 map：前端 / `storage/routes.json`。
    pub fn export(&self) -> BTreeMap<String, RouteExport> {
        let mut out = BTreeMap::new();
        for (name, uri) in &self.names {
            let mut methods = self
                .methods
                .get(name)
                .cloned()
                .unwrap_or_else(|| vec!["GET".into()]);
            methods.sort();
            out.insert(
                name.clone(),
                RouteExport {
                    uri: uri.clone(),
                    methods,
                },
            );
        }
        out
    }

    pub fn to_json(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(&self.export())
    }

    /// 写入 `storage/routes.json`（目录不存在则创建）。
    pub fn write_json_file(&self, path: impl AsRef<Path>) -> std::io::Result<()> {
        let path = path.as_ref();
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        let json = self
            .to_json()
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?;
        fs::write(path, json)
    }

    /// 生成给 TS/TSX 用的路由助手：`route.main.home()` ≡ Rust `route::main::home`。
    pub fn to_ts(&self) -> String {
        super::ts_routes::render_routes_ts(&self.export())
    }

    /// JSX 项目用的 `route()`（无 TypeScript 类型）。
    pub fn to_js(&self) -> String {
        let mut body = String::from(
            "/* @generated by Namix — DO NOT EDIT */\n\
             /* import { route } from './routes' → route('main.profile', { id: 1 }) */\n\n",
        );
        body.push_str("export const routes = {\n");
        for (name, item) in self.export() {
            let methods = item
                .methods
                .iter()
                .map(|m| serde_json::to_string(m).expect("route method is serializable"))
                .collect::<Vec<_>>()
                .join(", ");
            let name = serde_json::to_string(&name).expect("route name is serializable");
            let uri = serde_json::to_string(&item.uri).expect("route URI is serializable");
            body.push_str(&format!(
                "  {name}: {{ uri: {uri}, methods: [{methods}] }},\n"
            ));
        }
        body.push_str("};\n\n");
        body.push_str(
            "export function route(name, params) {\n\
               let uri = routes[name].uri;\n\
               if (params) {\n\
                 for (const [k, v] of Object.entries(params)) {\n\
                   uri = uri.replace(`:${k}`, String(v));\n\
                   uri = uri.replace(`*${k}`, String(v));\n\
                 }\n\
               }\n\
               if (uri.split('/').some((s) => s.startsWith(':') || s.startsWith('*'))) {\n\
                 throw new Error(`route('${name}') missing params: ${uri}`);\n\
               }\n\
               return uri;\n\
             }\n",
        );
        body
    }

    pub fn write_ts_file(&self, path: impl AsRef<Path>) -> std::io::Result<()> {
        let path = path.as_ref();
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(path, self.to_ts())
    }

    pub fn write_js_file(&self, path: impl AsRef<Path>) -> std::io::Result<()> {
        let path = path.as_ref();
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(path, self.to_js())
    }
}

fn has_unfilled_param(uri: &str) -> bool {
    uri.split('/')
        .any(|segment| segment.starts_with(':') || segment.starts_with('*'))
}

/// 类型化路由名（由 `route_names!` 生成，如 `route::user::login`）。
///
/// ```ignore
/// req.redirect_guest_to(route::user::login);
/// Route::get("/login", handler).name(route::user::login);
/// // 自定义字符串也行（会扫描进 route::billing::checkout）：
/// Route::get("/pay", h).name("billing.checkout");
/// // 动态参数：
/// req.url_with(route::user::profile, &[("id", "1")]);
/// ```
pub trait NamedRoute: Copy {
    fn route_name(self) -> &'static str;
}

/// `.name(...)` / 跳转 API 同时接受字符串与 [`NamedRoute`]。
pub trait IntoRouteName {
    fn into_route_name(self) -> String;
}

impl IntoRouteName for String {
    fn into_route_name(self) -> String {
        self
    }
}

impl IntoRouteName for &str {
    fn into_route_name(self) -> String {
        self.to_string()
    }
}

impl IntoRouteName for &String {
    fn into_route_name(self) -> String {
        self.clone()
    }
}

impl<R: NamedRoute> IntoRouteName for R {
    fn into_route_name(self) -> String {
        self.route_name().to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn same_name_and_uri_merge_distinct_methods() {
        let mut catalog = RouteCatalog::new();
        catalog.insert_with_method("posts.update", "/posts/:id", Some("PUT"));
        catalog.insert_with_method("posts.update", "/posts/:id", Some("PATCH"));
        catalog.insert_with_method("posts.update", "/posts/:id", Some("PATCH"));

        let route = &catalog.export()["posts.update"];
        assert_eq!(route.uri, "/posts/:id");
        assert_eq!(route.methods, ["PATCH", "PUT"]);
    }

    #[test]
    #[should_panic(expected = "registered with conflicting URIs")]
    fn same_name_with_different_uri_panics() {
        let mut catalog = RouteCatalog::new();
        catalog.insert_with_method("posts.show", "/posts/:id", Some("GET"));
        catalog.insert_with_method("posts.show", "/articles/:id", Some("GET"));
    }

    #[test]
    fn reverse_url_fills_colon_and_wildcard_params() {
        let mut catalog = RouteCatalog::new();
        catalog.insert("assets.show", "/teams/:team/assets/*path");

        assert_eq!(
            catalog.url(
                "assets.show",
                &[("team", "namix"), ("path", "images/logo.svg")]
            ),
            Some("/teams/namix/assets/images/logo.svg".into())
        );
        assert_eq!(catalog.url("assets.show", &[("team", "namix")]), None);
    }

    #[test]
    fn generated_js_fills_wildcards_and_checks_missing_values() {
        let mut catalog = RouteCatalog::new();
        catalog.insert("assets.show", "/assets/*path");

        let js = catalog.to_js();
        assert!(js.contains("uri = uri.replace(`*${k}`, String(v));"));
        assert!(js.contains("s.startsWith(':') || s.startsWith('*')"));
    }
}
