//! 把扁平 `main.login.submit` 编成与 Rust `route::main::login_submit` 同构的嵌套 TS。

use std::collections::BTreeMap;

use super::catalog::RouteExport;

pub fn render_routes_ts(map: &BTreeMap<String, RouteExport>) -> String {
    let mut body = String::from(
        "/* @generated by Namix — DO NOT EDIT */\n\
         /* Rust: AppRoute::Home / route::main::home  →  TS: route.home() / AppRoute.Home */\n\
         /* 带参: route.profile({ id: 1 })  或  字符串名 route(AppRoute.Profile, { id: 1 }) */\n\n",
    );

    body.push_str("export const routes = {\n");
    for (name, item) in map {
        let methods = item
            .methods
            .iter()
            .map(|m| ts_string(m))
            .collect::<Vec<_>>()
            .join(", ");
        let name = ts_string(name);
        let uri = ts_string(&item.uri);
        body.push_str(&format!(
            "  {name}: {{ uri: {uri}, methods: [{methods}] as const }},\n"
        ));
    }
    body.push_str("} as const;\n\n");
    body.push_str("export type RouteName = keyof typeof routes;\n\n");
    body.push_str(&render_app_route_enum(map));

    body.push_str(
        "function fill(uri: string, params?: Record<string, string | number>): string {\n\
           let out = uri;\n\
           if (params) {\n\
             for (const [k, v] of Object.entries(params)) {\n\
               out = out.replace(`:${k}`, String(v));\n\
               out = out.replace(`*${k}`, String(v));\n\
             }\n\
           }\n\
           if (out.split('/').some((s) => s.startsWith(':') || s.startsWith('*'))) {\n\
             throw new Error(`missing route params: ${out}`);\n\
           }\n\
           return out;\n\
         }\n\n\
         /** 字符串名解析（兼容旧写法） */\n\
         export function resolveRoute(\n\
           name: RouteName,\n\
           params?: Record<string, string | number>\n\
         ): string {\n\
           return fill(routes[name].uri, params);\n\
         }\n\n",
    );

    // 嵌套 route.home / route.login.submit（来自 .name("login.submit")）
    body.push_str("/** 与命名路由短名同构：route.login() ≡ .name(\"login\") */\n");
    body.push_str("export const route = ");
    body.push_str(&render_nested(map));
    body.push_str(" as const;\n\n");

    // 默认导出兼用：route('main.home') 与 route.main.home()
    body.push_str(
        "type RouteFn = {\n\
           (name: RouteName, params?: Record<string, string | number>): string;\n\
         } & typeof route;\n\n\
         const routeCallable = Object.assign(\n\
           ((name: RouteName, params?: Record<string, string | number>) =>\n\
             resolveRoute(name, params)) as RouteFn,\n\
           route\n\
         );\n\n\
         export default routeCallable;\n",
    );

    body
}

fn render_app_route_enum(map: &BTreeMap<String, RouteExport>) -> String {
    let mut body = String::from(
        "/** 与 Rust `AppRoute::Login` 对齐；`route(AppRoute.Login)` ≡ `route.login()` */\n\
         export const AppRoute = {\n",
    );
    for name in map.keys() {
        if name.starts_with("__") {
            continue;
        }
        let key = route_enum_key(name);
        body.push_str(&format!("  {key}: {},\n", ts_string(name)));
    }
    body.push_str(
        "} as const;\n\
         export type AppRoute = (typeof AppRoute)[keyof typeof AppRoute];\n\n",
    );
    body
}

fn route_enum_key(name: &str) -> String {
    let pascal = name
        .split(['.', '-', '_'])
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect::<String>();
    if pascal.is_empty() || !is_ts_identifier(&pascal) {
        format!("[{}]", ts_string(name))
    } else {
        pascal
    }
}

fn render_nested(map: &BTreeMap<String, RouteExport>) -> String {
    #[derive(Default)]
    struct Node {
        children: BTreeMap<String, Node>,
        /// (full_name, uri)
        leaf: Option<(String, String)>,
    }

    let mut root = Node::default();
    for (name, item) in map {
        if name.starts_with("__") {
            continue;
        }
        let parts: Vec<&str> = name.split('.').collect();
        if parts.is_empty() {
            continue;
        }
        let mut cur = &mut root;
        for (i, part) in parts.iter().enumerate() {
            let key = part.replace('-', "_");
            if i + 1 == parts.len() {
                let child = cur.children.entry(key).or_default();
                child.leaf = Some((name.clone(), item.uri.clone()));
            } else {
                cur = cur.children.entry(key).or_default();
            }
        }
    }

    fn emit_props(node: &Node, indent: usize) -> String {
        let pad_in = "  ".repeat(indent + 1);
        let mut s = String::new();
        for (key, child) in &node.children {
            let ident = ts_ident(key);
            s.push_str(&format!(
                "{pad_in}{ident}: {},\n",
                emit_value(child, indent + 1)
            ));
        }
        s
    }

    fn emit_value(node: &Node, indent: usize) -> String {
        let pad = "  ".repeat(indent);
        let pad_in = "  ".repeat(indent + 1);
        if let Some((full, uri)) = &node.leaf {
            let params = path_params(uri);
            let full_literal = ts_string(full);
            let uri_literal = ts_string(uri);
            let child_props = emit_props(node, indent);
            // 注意：不能写 `name`——Function.name 只读，会在运行时抛错
            if params.is_empty() {
                format!(
                    "Object.assign(() => fill(routes[{full_literal}].uri), {{\n\
                     {pad_in}routeName: {full_literal} as const,\n\
                     {pad_in}uri: {uri_literal} as const,\n\
                     {child_props}{pad}}})"
                )
            } else {
                let typ = params
                    .iter()
                    .map(|p| format!("{}: string | number", ts_type_key(p)))
                    .collect::<Vec<_>>()
                    .join("; ");
                format!(
                    "Object.assign(\n\
                     {pad_in}(params: {{ {typ} }}) => fill(routes[{full_literal}].uri, params),\n\
                     {pad_in}{{\n\
                     {pad_in}  routeName: {full_literal} as const,\n\
                     {pad_in}  uri: {uri_literal} as const,\n\
                     {child_props}{pad_in}}}\n\
                     {pad})"
                )
            }
        } else {
            format!("{{\n{}{pad}}}", emit_props(node, indent))
        }
    }

    format!("{{\n{}}}", emit_props(&root, 0))
}

fn path_params(uri: &str) -> Vec<String> {
    let mut params = Vec::new();
    for segment in uri.split('/') {
        let Some(param) = segment
            .strip_prefix(':')
            .or_else(|| segment.strip_prefix('*'))
        else {
            continue;
        };
        if !param.is_empty() && !params.iter().any(|existing| existing == param) {
            params.push(param.to_string());
        }
    }
    params
}

fn ts_ident(s: &str) -> String {
    if is_ts_identifier(s) {
        s.to_string()
    } else {
        format!("[{}]", ts_string(s))
    }
}

fn ts_type_key(s: &str) -> String {
    if is_ts_identifier(s) {
        s.to_string()
    } else {
        ts_string(s)
    }
}

fn is_ts_identifier(s: &str) -> bool {
    let mut chars = s.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    (first.is_ascii_alphabetic() || matches!(first, '_' | '$'))
        && chars.all(|c| c.is_ascii_alphanumeric() || matches!(c, '_' | '$'))
}

fn ts_string(s: &str) -> String {
    let mut out = String::from("\"");
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn route(uri: &str) -> RouteExport {
        RouteExport {
            uri: uri.into(),
            methods: vec!["GET".into()],
        }
    }

    #[test]
    fn wildcard_is_a_required_typed_parameter() {
        let map = BTreeMap::from([("assets.show".into(), route("/teams/:team/assets/*path"))]);

        let ts = render_routes_ts(&map);
        assert!(ts.contains("params: { team: string | number; path: string | number }"));
        assert!(ts.contains("out = out.replace(`*${k}`, String(v));"));
        assert!(ts.contains("s.startsWith(':') || s.startsWith('*')"));
        assert!(ts.contains("export const AppRoute"));
        assert!(ts.contains("AssetsShow: \"assets.show\""));
    }

    #[test]
    fn unsafe_parameter_names_are_quoted_type_keys() {
        let map = BTreeMap::from([("users.show".into(), route("/users/:user-id"))]);

        let ts = render_routes_ts(&map);
        assert!(ts.contains("params: { \"user-id\": string | number }"));
    }

    #[test]
    fn route_strings_are_emitted_as_valid_json_literals() {
        let map = BTreeMap::from([("odd.\"name".into(), route("/line\n/:id"))]);

        let ts = render_routes_ts(&map);
        assert!(ts.contains("\"odd.\\\"name\""));
        assert!(ts.contains("\"/line\\n/:id\""));
    }
}
