// @generated by namix-build — DO NOT EDIT
// 新增 .rs 后 cargo check 自动注册。

pub mod auth;
pub mod chat;
pub mod dashboard;
pub mod demo;
pub mod home;
pub mod mailbox;
pub mod me;
pub mod posts;
pub mod profile;
pub mod realtime;
