//! 从 `storage/routes.json` 生成前端用的 `route()` 助手。

use std::collections::BTreeMap;
use std::fs;
use std::path::PathBuf;

use crate::project::Project;

#[derive(serde::Deserialize)]
struct RouteExport {
    uri: String,
    #[serde(default)]
    methods: Vec<String>,
}

pub fn routes(project: &Project) -> Result<(), String> {
    let json_path = find_routes_json(project)?;
    let raw =
        fs::read_to_string(&json_path).map_err(|e| format!("读 {}: {e}", json_path.display()))?;
    let map: BTreeMap<String, RouteExport> =
        serde_json::from_str(&raw).map_err(|e| format!("解析 routes.json: {e}"))?;

    let jsx = project.root.join("frontend/src/routes.js").is_file()
        || project.root.join("frontend/src/main.jsx").is_file();
    let out = prefer_frontend_out(project, jsx);
    let body = if jsx {
        render_js(&map)
    } else {
        render_ts(&map)
    };
    if let Some(parent) = out.parent() {
        fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    fs::write(&out, body).map_err(|e| format!("写 {}: {e}", out.display()))?;
    println!("✓ {}", out.display());
    println!("  import {{ route }} from './routes'");
    println!("  route('main.profile', {{ id: 1 }})");
    Ok(())
}

fn prefer_frontend_out(project: &Project, jsx: bool) -> PathBuf {
    let views = project.app_dir.join("src/views");
    if views.is_dir() {
        return views.join(if jsx { "routes.js" } else { "routes.ts" });
    }
    let fe_dir = project.root.join("frontend/src");
    if fe_dir.is_dir() {
        return fe_dir.join(if jsx { "routes.js" } else { "routes.ts" });
    }
    let storage = project.app_dir.join("storage");
    storage.join(if jsx { "routes.js" } else { "routes.ts" })
}

fn find_routes_json(project: &Project) -> Result<PathBuf, String> {
    let candidates = [
        project.app_dir.join("storage/routes.json"),
        project.root.join("storage/routes.json"),
        project.root.join("app/storage/routes.json"),
    ];
    for p in candidates {
        if p.is_file() {
            return Ok(p);
        }
    }
    Err("找不到 storage/routes.json — 先启动一次 app（Boot 会写出），或确认 cwd 在项目根".into())
}

fn render_ts(map: &BTreeMap<String, RouteExport>) -> String {
    let mut body = String::from(
        "/* @generated by Namix — DO NOT EDIT */\n\
         /* import { route } from './routes' → route('main.profile', { id: 1 }) */\n\n",
    );
    body.push_str("export const routes = {\n");
    for (name, item) in map {
        let methods = item
            .methods
            .iter()
            .map(|m| format!("\"{m}\""))
            .collect::<Vec<_>>()
            .join(", ");
        let uri = item.uri.replace('\\', "\\\\").replace('"', "\\\"");
        body.push_str(&format!(
            "  \"{name}\": {{ uri: \"{uri}\", methods: [{methods}] as const }},\n"
        ));
    }
    body.push_str("} as const;\n\n");
    body.push_str("export type RouteName = keyof typeof routes;\n\n");
    body.push_str(
        "export function route(\n\
           name: RouteName,\n\
           params?: Record<string, string | number>\n\
         ): string {\n\
           let uri: string = routes[name].uri;\n\
           if (params) {\n\
             for (const [k, v] of Object.entries(params)) {\n\
               uri = uri.replace(`:${k}`, String(v));\n\
             }\n\
           }\n\
           if (uri.split('/').some((s) => s.startsWith(':'))) {\n\
             throw new Error(`route('${name}') missing params: ${uri}`);\n\
           }\n\
           return uri;\n\
         }\n",
    );
    body
}

fn render_js(map: &BTreeMap<String, RouteExport>) -> String {
    let mut body = String::from(
        "/* @generated by Namix — DO NOT EDIT */\n\
         /* import { route } from './routes' → route('main.profile', { id: 1 }) */\n\n",
    );
    body.push_str("export const routes = {\n");
    for (name, item) in map {
        let methods = item
            .methods
            .iter()
            .map(|m| format!("\"{m}\""))
            .collect::<Vec<_>>()
            .join(", ");
        let uri = item.uri.replace('\\', "\\\\").replace('"', "\\\"");
        body.push_str(&format!(
            "  \"{name}\": {{ uri: \"{uri}\", methods: [{methods}] }},\n"
        ));
    }
    body.push_str("};\n\n");
    body.push_str(
        "export function route(name, params) {\n\
           let uri = routes[name].uri;\n\
           if (params) {\n\
             for (const [k, v] of Object.entries(params)) {\n\
               uri = uri.replace(`:${k}`, String(v));\n\
             }\n\
           }\n\
           if (uri.split('/').some((s) => s.startsWith(':'))) {\n\
             throw new Error(`route('${name}') missing params: ${uri}`);\n\
           }\n\
           return uri;\n\
         }\n",
    );
    body
}
