// @generated by namix-build — DO NOT EDIT
// 新增 .rs 后 cargo check 自动注册。

pub mod login_log;
pub mod note;
pub mod post;
pub mod post_tag;
pub mod profile;
pub mod registry;
pub mod tag;
pub mod user;
